/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";
import BgLayout from "@/layouts/bg-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
  bg: BgLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  home: () => import("@/views/home/index.vue"),
  ride_carpool: () => import("@/views/ride/carpool/index.vue"),
  ride_grab: () => import("@/views/ride/grab/index.vue"),
  ride_order: () => import("@/views/ride/order/index.vue"),
  ride_profile: () => import("@/views/ride/profile/index.vue"),
  ride_review: () => import("@/views/ride/review/index.vue"),
  system_about: () => import("@/views/system/about/index.vue"),
  system_home: () => import("@/views/system/home/index.vue"),
  system_manage_driver: () => import("@/views/system/manage/driver/index.vue"),
  system_manage_order: () => import("@/views/system/manage/order/index.vue"),
  system_manage_passenger: () => import("@/views/system/manage/passenger/index.vue"),
  system_manage_review: () => import("@/views/system/manage/review/index.vue"),
  system_plugin_barcode: () => import("@/views/system/plugin/barcode/index.vue"),
  system_plugin_charts_antv: () => import("@/views/system/plugin/charts/antv/index.vue"),
  system_plugin_charts_echarts: () => import("@/views/system/plugin/charts/echarts/index.vue"),
  system_plugin_charts_vchart: () => import("@/views/system/plugin/charts/vchart/index.vue"),
  system_plugin_copy: () => import("@/views/system/plugin/copy/index.vue"),
  system_plugin_editor_markdown: () => import("@/views/system/plugin/editor/markdown/index.vue"),
  system_plugin_editor_quill: () => import("@/views/system/plugin/editor/quill/index.vue"),
  system_plugin_excel: () => import("@/views/system/plugin/excel/index.vue"),
  system_plugin_gantt_dhtmlx: () => import("@/views/system/plugin/gantt/dhtmlx/index.vue"),
  system_plugin_gantt_vtable: () => import("@/views/system/plugin/gantt/vtable/index.vue"),
  system_plugin_icon: () => import("@/views/system/plugin/icon/index.vue"),
  system_plugin_map: () => import("@/views/system/plugin/map/index.vue"),
  system_plugin_pdf: () => import("@/views/system/plugin/pdf/index.vue"),
  system_plugin_pinyin: () => import("@/views/system/plugin/pinyin/index.vue"),
  system_plugin_print: () => import("@/views/system/plugin/print/index.vue"),
  system_plugin_swiper: () => import("@/views/system/plugin/swiper/index.vue"),
  system_plugin_tables_vtable: () => import("@/views/system/plugin/tables/vtable/index.vue"),
  system_plugin_typeit: () => import("@/views/system/plugin/typeit/index.vue"),
  system_plugin_video: () => import("@/views/system/plugin/video/index.vue"),
  "system_user-center": () => import("@/views/system/user-center/index.vue"),
};
